import exp from "node:constants";
import { RestaurantType, Collection, Cuisine, Moods } from "./types";

export const restaurants: RestaurantType[] = [
  {
    id: "1",
    name: "Paradise Biryani",
    image: "https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    rating: 4.2,
    deliveryTime: 25,
    costForTwo: 500,
    discount: "40% OFF up to ₹80",
    offers: "40% OFF up to ₹80 | Use code TRYNEW",
    promoted: true,
  },
  {
    id: "2",
    name: "Shah Ghouse Hotel & Restaurant",
    image: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg",
    cuisines: ["Biryani", "Mughlai", "North Indian"],
    rating: 4.3,
    deliveryTime: 30,
    costForTwo: 400,
    discount: "50% OFF up to ₹100",
    offers: "50% OFF up to ₹100 | Use code WELCOME50",
  },
  {
    id: "3",
    name: "Spice 6 Global Cuisine",
    image: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg",
    cuisines: ["Chinese", "North Indian", "Continental"],
    rating: 3.8,
    deliveryTime: 35,
    costForTwo: 600,
  },
  {
    id: "4",
    name: "Chutneys",
    image: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg",
    cuisines: ["South Indian", "Andhra"],
    rating: 4.5,
    deliveryTime: 20,
    costForTwo: 350,
    discount: "15% OFF up to ₹300",
    offers: "FREE DELIVERY",
    promoted: true,
  },
  {
    id: "5",
    name: "Mehfil Restaurant",
    image: "https://images.pexels.com/photos/1603901/pexels-photo-1603901.jpeg",
    cuisines: ["Biryani", "North Indian", "Chinese"],
    rating: 4.1,
    deliveryTime: 28,
    costForTwo: 450,
    discount: "₹125 OFF",
    offers: "₹125 OFF on orders above ₹249 | Use code FLAT125",
  },
  {
    id: "6",
    name: "Cafe Bahar",
    image: "https://images.pexels.com/photos/941869/pexels-photo-941869.jpeg",
    cuisines: ["Biryani", "Chinese", "Mughlai"],
    rating: 4.0,
    deliveryTime: 32,
    costForTwo: 400,
  },
  {
    id: "7",
    name: "KFC",
    image: "https://images.pexels.com/photos/115740/pexels-photo-115740.jpeg",
    cuisines: ["Fast Food", "Burgers", "American"],
    rating: 4.1,
    deliveryTime: 22,
    costForTwo: 450,
    discount: "20% OFF up to ₹50",
    offers: "20% OFF up to ₹50 | Use code PARTY",
  },
  {
    id: "8",
    name: "Domino's Pizza",
    image: "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg",
    cuisines: ["Pizza", "Fast Food", "Italian"],
    rating: 4.2,
    deliveryTime: 25,
    costForTwo: 400,
    promoted: true,
  },
  {
    id: "9",
    name: "Cream Stone",
    image: "https://images.pexels.com/photos/1352281/pexels-photo-1352281.jpeg",
    cuisines: ["Ice Cream", "Desserts"],
    rating: 4.4,
    deliveryTime: 20,
    costForTwo: 250,
    discount: "FREE Delivery",
    offers: "FREE delivery on orders above ₹399 | Use code CSBOGO",
  },
  {
    id: "10",
    name: "Pista House",
    image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg",
    cuisines: ["Bakery", "Desserts", "North Indian"],
    rating: 4.3,
    deliveryTime: 22,
    costForTwo: 350,
  },
  {
    id: "11",
    name: "McDonald's",
    image: "https://images.pexels.com/photos/2983101/pexels-photo-2983101.jpeg",
    cuisines: ["Burgers", "Fast Food", "Beverages"],
    rating: 4.2,
    deliveryTime: 20,
    costForTwo: 400,
    discount: "FREE McAloo Tikki Burger",
    offers: "FREE McAloo Tikki Burger on orders above ₹399",
  },
  {
    id: "12",
    name: "Kritunga Restaurant",
    image: "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg",
    cuisines: ["Andhra", "South Indian", "Biryani"],
    rating: 4.0,
    deliveryTime: 32,
    costForTwo: 500,
    promoted: true,
  },
];

export const collections: Collection[] = [
  {
    id: "1",
    title: "Trending This Week",
    image: "https://images.pexels.com/photos/696218/pexels-photo-696218.jpeg",
    places: 30,
  },
  {
    id: "2",
    title: "Best of Hyderabad",
    image: "https://images.pexels.com/photos/1486693/pexels-photo-1486693.jpeg",
    places: 45,
  },
  {
    id: "3",
    title: "Newly Opened Restaurants",
    image: "https://images.pexels.com/photos/1152237/pexels-photo-1152237.jpeg",
    places: 18,
  },
  {
    id: "4",
    title: "Great Cafes",
    image: "https://images.pexels.com/photos/683039/pexels-photo-683039.jpeg",
    places: 29,
  },
  {
    id: "5",
    title: "Premium Dining",
    image: "https://images.pexels.com/photos/1307698/pexels-photo-1307698.jpeg",
    places: 25,
  },
  {
    id: "6",
    title: "Best Biryanis",
    image:
      "https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg",
    places: 22,
  },
];

export const cuisines: Cuisine[] = [
  { id: "1", name: "Biryani", count: 142 },
  { id: "2", name: "North Indian", count: 121 },
  { id: "3", name: "Chinese", count: 98 },
  { id: "4", name: "South Indian", count: 87 },
  { id: "5", name: "Fast Food", count: 76 },
  { id: "6", name: "Andhra", count: 64 },
  { id: "7", name: "Mughlai", count: 53 },
  { id: "8", name: "Italian", count: 42 },
  { id: "9", name: "Continental", count: 38 },
  { id: "10", name: "Desserts", count: 33 },
  { id: "11", name: "Beverages", count: 29 },
  { id: "12", name: "Pizza", count: 27 },
  { id: "13", name: "Burgers", count: 25 },
  { id: "14", name: "Ice Cream", count: 22 },
  { id: "15", name: "Bakery", count: 21 },
  { id: "16", name: "American", count: 18 },
];

export const moods: Moods[] = [
  {
    id: "1",
    moodType: "Eat Traditional/Comfort Food",
    // image:"https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg",
    image:
      "https://images.pexels.com/photos/28674705/pexels-photo-28674705.jpeg",
    tags: ["north indian", "biryani", "paratha", "dal", "homestyle"],
    restaurant: restaurants[1],
  },
  {
    id: "2",
    moodType: "Proteinaceous",
    image: "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg",
    tags: [
      "paneer",
      "chicken",
      "mutton",
      "eggs",
      "prawns",
      "fish",
      "non-veg",
      "paneer-burger",
      "paneer-pizza",
      "paneer-biryani",
      "chicken-burger",
      "chicken-pizza",
      "mutton-pizza",
      "chicken-burger",
      "chicken-biryani",
      "mutton-biryani",
      "fish-biryani",
      "prawn-biryani",
      "egg-biryani",
      "non-veg-curries",
    ],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[9],
  },
  {
    id: "3",
    moodType: "Hydrating",
    image: "https://images.pexels.com/photos/1459338/pexels-photo-1459338.jpeg",
    tags: [
      "fruit-juices",
      "milkshakes",
      "fruit-salads",
      "juice",
      "coconut water",
      "smoothie",
      "buttermilk",
    ],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[10],
  },

  {
    id: "4",
    moodType: "Healthy",
    image: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg",
    tags: ["salad", "grilled", "low-cal", "vegan", "quinoa"],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[4],
  },
  {
    id: "5",
    moodType: "Sweet Craving",
    image: "https://images.pexels.com/photos/3026806/pexels-photo-3026806.jpeg",
    tags: ["dessert", "ice cream", "cake", "gulab jamun"],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[5],
  },
  {
    id: "6",
    moodType: "Spice Craving",
    // image: "https://images.pexels.com/photos/5936/food-plate-spicy.jpg",
    image:
      "https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg",
    tags: [
      "biryani",
      "noodles",
      "pani-puri",
      "vada-pav",
      "chole-bhature",
      "masalas",
      "curries",
      "grilled",
      "manchuria",
      "fried-rice",
    ],
    // restaurant: {/* Dummy restaurant object */}
    restaurant: restaurants[6],
  },
  {
    id: "7",
    moodType: "Something Tangy/Sour",
    image: "https://images.pexels.com/photos/1435895/pexels-photo-1435895.jpeg",
    tags: [
      "tangy",
      "citrusy",
      "zingy",
      "sambar",
      "rasam",
      "chutneys",
      "lemon",
      "raw-mango",
      "chaats",
    ],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[7],
  },
  {
    id: "8",
    moodType: "Ready to Eat",
    image: "https://images.pexels.com/photos/750073/pexels-photo-750073.jpeg",
    tags: ["quick", "instant", "microwaveable"],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[8],
  },
  {
    id: "9",
    moodType: "Gut-Brain Axis",
    image: "https://images.pexels.com/photos/7195234/pexels-photo-7195234.jpeg",
    tags: ["fermented", "probiotic", "yogurt", "kimchi", "idli"],
    // restaurant: {/* Dummy restaurant object */}
    restaurant: restaurants[2],
  },

  {
    id: "10",
    moodType: "Eat to Beat Depression",
    image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
    tags: ["omega-3", "leafy greens", "mood-boosting"],
    // restaurant: {/* Dummy restaurant object */},
    restaurant: restaurants[3],
  },
];
